version: '3.8'
services:
  app:
    build:
      context: ./build/
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./build/apache/laravel.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=blog
      - DB_USERNAME=dbuser
      - DB_PASSWORD=dbpass
    depends_on:
      - db
    networks:
      - webapp
    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_ROOT_PASSWORD=password1
    volumes:
      - db_blog:/var/lib/mysql
    networks:
      - webapp
    ports:
      - "3306:3306"
networks:
  webapp:
volumes:
  db_blog: